{% set name = "cycler" %}
{% set version = "0.12.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88bb128f02ba341da8ef447245a9e138fae777f6a23943da4540077d3601eb1c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools >=61
    - wheel
  run:
    - python

test:
  imports:
    - cycler
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://matplotlib.org/cycler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Composable style cycles.
  description: |
    Cycler is a package used to create composable style cycles.
  doc_url: http://matplotlib.org/cycler
  doc_source_url: https://github.com/matplotlib/cycler/blob/master/doc/source/index.rst
  dev_url: https://github.com/matplotlib/cycler

extra:
  recipe-maintainers:
    - pelson
    - tacaswell
    - janschulz
    - ocefpaf
