package:
  name: cycler
  version: 0.10.0

source:
  url: https://github.com/matplotlib/cycler/archive/v0.10.0.tar.gz
  fn: cycler-v0.10.0.tar.gz
  sha256: b6d217635e03024196225367b1a438996dbbf0271bec488f00584f0e7dc15cfa

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - six
  run:
    - python
    - six

test:
  imports:
    - cycler

about:
  home: http://github.com/matplotlib/cycler
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Composable style cycles.'

extra:
  recipe-maintainers:
    - pelson
    - tacaswell
    - janschulz
    - ocefpaf
