
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27  
    - CONDA_PY=34  
    - CONDA_PY=35  
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in forge.yml.
    - secure: "s4zYvxjIzhy98GWky9h4Nq5dmNpityKeie747EcSVWqJ/xlsvZEiwE7hyRj+qbjlh6m3NRiDYi2BWdKov/heMboheFb9j/Sh/Sa17pOMOAdIBcr4k6VS7ecwpzMwxVNDOjAuiWEVY6TcUAiRwgqvSI4DFNeTfORNNgndJvRMd1KoI/Azw+DElkG6jgGhCqA0LU6TEhpjsRQ3hSmJ7XQgWeyydcgrRC2npf1ZpP4VkrWeHprfJe+v0z/lipAzs3Gyg2hsVwrBX+hUSLiOzAjFDX2gTJeNMEosHeSy/3o8T9J1z9lgjDe5+YEf9KXaO2YeW1g1gbF2DfqiwsGmdHP+nqDTg0H2LybwZJ8miOGWVyUc1G6RieRKYVTa+jB0RBwubVQSHgk3ibY+kmOGDuqx9niWgePZnJGzosmVv/vZwIAAPrktwgXBHXsDtOr+jHaeypmhY9U4Ll2bJ2WkCqiVxbqtPDbn4nmWihJw29JnSEYKcmNtGFhoSm2NgHTSgmwMhxfjfbDPqz1QMTOC+9MNMixzphc7KqeJtSmg8bszKuztLbEe3qeXNfEXaAGMwgQWy76q6750FGr6+r65Xo6P+vTmBedVWuPggG9T0G+TvTJ29iZnzlywDq508IWw+LRAdwVbL9PLWXHIq+rBHJDrHtKCI7OPURlmmRrXJoe2P10="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
