
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27  
    - CONDA_PY=34  
    - CONDA_PY=35  
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in forge.yml.
    - secure: "Oq9VH7ktl1YK0NSPzFKeBkwh9vFEPenR/NjcM13NXuMZQ7ttsgX7XGYiSsAGOciZd1kCv0wdrxmcm36G77Sxr13V7kXRhHKRcksocgvLJuIEJXzme5nPnNge6ULXmi/Sy2MO5/QCHnKzN4GuQiE9OFjyHf3F/HYsOsMjXd1q+eYYS/qwX6eqq4O9wwLsGJgZXszm93LYcu3s7QT5RfE1/YfgasqH5DzQHFPPkVrWYGr7iKKSvEKDQmkjTu1orqO+/l+KGPZvk6KEs5gGeskzldrunWiZnw+ECYRk0MBaNwn2+JL1ISZfcaDcL4oVRLVdFOXfT5StDpwHDFnKoZk7bKGH+vVp3SVvxmOg3CnrnQCAQq+5p3f9rbXZsLLYexD6wDwflW0HHngehrJ72YOxRDVwTp0ngUvJ2F2UgzYCk5nC3RV0LifBtRfzCmxxYQM7yjxOXMj6mnF8qy3TMsrvCAa28tcyMy0b1XMZhvOGgF0rBKrKdpKEHI5Ka4jwpXShWIPJg+e6vtFZ3HMbzlyNWt+o4+XfilJBjnBkMl7tAP42DxyzCVSb9YDJH4csnR5Vn74lQ6bRZIrnV9zsE/RU5qkutbsQE6hVG+TdjfPyiCSRbUIXXGq5ojXnx5Szd2EaUvial5nLg6vWt/vKaIt0mKioeZ3igTWjO4JcZR1bhCU="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
