# This file was generated automatically by conda-forge (vn 0.1.0).




language: objective-c



env:


  matrix:
    
    - CONDA_PY=27  
    
    - CONDA_PY=34  
    
    - CONDA_PY=35  
    



  global:

    # The BINSTAR_TOKEN secure variable. This is defined canonically in forge.yml.
    - secure: "L7sEVArGuYoPFlqa1ny/jEyn6IL7qNGhEPHvGqRKBPJDwz9wWtMJ5u7LD30L+PRdznAdgzHfX1CJ4yDBQkudqIO3eoO9cjOVswaAvXkaLypVa+NLbgkgkjCXmqNTZujyVS/tbtoOjpk+4HI2lWXiCoIsOdcJRlt3DuY8zD/TkZFAaNdvFJY3qFGII7eFQYeeKXhw0Pni7eZV0zToTQrR+0Vv8cFIijomS07MaWF6eavAz7mCqRf67826ZZrThiDiyTVBeGZq8MuHJwy/q4BVRpuFsMSgSqhvVQNrlxMIUYzRpbsPz92PbMEef0V3TREVxFNETgtIIKEOw34dQbGCujqveh5AwM8P7/5K2oyu7s4NVKHEzue2LHNBDuDfCn9nDrl7JmO2cfBbIrdeEyOENiBgE+1u/7lQ7lcFRZCvU8++HKV3BMQijjq1We76TvD3EYQo4TI6jazkILcsASaLoy+CHqiHA4XdFlybwtDuE5PRyJG8nrp5kj2Rl6oAHOeEmqAQiMUnVQHCxKcoTg3YriCzwD2gd4IOuCwxjh+Tf8A4p9iTsFFeaLAch5Yl6XwUIjtX/RHbVEqahdXLqTbDwl1i1tf9GKE27j1NOE36fi5CvKTOS37T3Ql687+V652o3juasakWVhLbY5JzuWwNBbadTWxXVL+aJq3M2a7zl04="





install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
